version: '3.9'

services:
  mlflow_example:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: ml_service:$USER
    container_name: ml_service_$USER
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 1488:8890
    environment:
      - MLFLOW_TRACKING_URI=http://158.160.2.37:5000/
      - DEFAULT_RUN_ID=edfad2bc1f1e4681a4174ee5bb09bd35
      - EVIDENTLY_URL=http://158.160.2.37:8000/
      - EVIDENTLY_PROJECT_ID=019d39e4-f3ef-7544-911a-6f1d0f4cf1fe
      - DRIFT_BATCH_SIZE=10
      - DRIFT_CHECK_INTERVAL_SECONDS=20

    command: uvicorn main:app --host 0.0.0.0 --port 8890

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_$USER
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - mlflow_example